# Generated by Django 2.2.1 on 2019-05-29 17:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imdb_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('imdb_score', models.FloatField(blank=True, null=True)),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('Action', 'Action'), ('Adult', 'Adult'), ('Adventure', 'Adventure '), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Film Noir', 'Film Noir'), ('Game-Show', 'Game-Show'), ('History', 'History'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Music', 'Music'), ('Mystery', 'Mystery'), ('News', 'News'), ('Reality-TV', 'Reality-TV'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Short', 'Short'), ('Sport', 'Sport'), ('Talk-Show', 'Talk-Show'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], max_length=219)),
                ('popularity', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
